server:
#    热部署
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: hr
    password: h123456
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      charset: utf-8
      force: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
  profiles:
    active: product
mybatis:
  type-aliases-package: com.demo2.entity